---
inputs:
  - type: git
    branch: ${PIPELINE_REPO_BRANCH}
    service: ${PIPELINE_REPO}
    path: .deploy_blue_green_pipeline
  - type: git
    branch: ${DEFINITIONS_BRANCH}
    service: ${TEKTON_CATALOG_REPO}
    path: git
  - type: git
    branch: ${DEFINITIONS_BRANCH}
    service: ${TEKTON_CATALOG_REPO}
    path: container-registry
  - type: git
    service: ${TEKTON_CATALOG_REPO}
    branch: ${DEFINITIONS_BRANCH}
    path: kubernetes-service
  - type: git
    service: ${TEKTON_CATALOG_REPO}
    branch: ${DEFINITIONS_BRANCH}
    path: toolchain
  - type: git
    branch: ${DEFINITIONS_BRANCH}
    service: ${TEKTON_CATALOG_REPO}
    path: cra
  - type: git
    service: ${TEKTON_CATALOG_REPO}
    branch: ${DEFINITIONS_BRANCH}
    path: devops-insights
  - type: git
    branch: ${DEFINITIONS_BRANCH}
    service: ${TEKTON_CATALOG_REPO}
    path: linter
  - type: git
    branch: ${DEFINITIONS_BRANCH}
    service: ${TEKTON_CATALOG_REPO}
    path: tester
  - type: git
    branch: ${DEFINITIONS_BRANCH}
    service: ${TEKTON_CATALOG_REPO}
    path: utils
triggers:
  - type: git
    name: blue-green-commit-push
    eventListener: blue-green-${GIT_COMMIT_EVENT_LISTENER_NAME}
    service: ${INVENTORY_REPO}
    branch: ${INVENTORY_BRANCH}
    events: { "push": true }
  - type: manual
    name: blue-green-manual-run
    eventListener: blue-green-manual-run
    properties: []
  - type: manual  
    name: switch-blue-green
    eventListener: switch-blue-green
    properties: []
  
properties:
  - type: secure
    name: toolchain-apikey
    value: ${API_KEY}
  - name: apikey
    value: ${API_KEY}
    type: SECURE
  - name: registry-region
    value: ${REGISTRY_REGION_ID}
    type: text
  - name: registry-namespace
    value: ${REGISTRY_NAMESPACE}
    type: text
  - name: image-name
    value: ${APP_NAME}
    type: text
  - name: app-name
    value: ${APP_NAME}
    type: text
  - name: dev-cluster-namespace
    value: ${PROD_CLUSTER_NAMESPACE}
    type: text
  - name: dev-region
    value: ${PROD_REGION_ID}
    type: text
  - name: cluster-name
    value: ${PROD_CLUSTER_NAME}
    type: text
  - name: dev-resource-group
    value: ${PROD_RESOURCE_GROUP}
    type: text
  - name: deployment-strategy
    value: ${DEPLOYMENT_STRATEGY}
    type: text
  - name: inventoryRepo
    value: ${INVENTORY_REPO}
    type: integration
    path: parameters.repo_url
  - name: repository
    value: ${APP_REPO}
    type: integration
    path: parameters.repo_url  
  - name: branch
    type: text
    value: ${APP_REPO_BRANCH}
  - name: commons-hosted-region
    value: ${COMMONS_HOSTED_REGION}
    type: text
  - name: insights
    value: ${INSIGHTS}
    type: integration
    path: service_id 
